grem11n/awesome-it-communities-ua

README.md
=> Add IT KPI list

.github/workflows/main.yml, README.md
* Add Awesome_bot
* Add CI badges
Closes awesome_bot
=> Add badges and awesome_bot

README.md
**[Insert the name of a community here]**:
PostgreSQL Ukraine
_[Insert the URL to the community here]_
https://t.me/PostgresUkraine
[Explain what your community is about]
PostgreSQL community in Ukraine to help/support people and discuss various Postgres-related topics.
=> Add PostgresUkraine telegram channel

README.md
**PHP Friends Club Ukraine Chat**:
_https://t.me/phpfriendsclub_chat_
Чат про PHP та Web розробку.
=> Add PHP Ukraine telegram channel

.github/pull_request_template.md
=> fix template

README.md
**React Kyiv**:
_https://t.me/reactkyiv_
Telegram chat for React developers
=> Add React Kyiv

README.md
**FAANG Interview**:
_https://t.me/FaangInterview_
Это украинская группа по подготовке к интервью. Цель: обсуждение вопросов по подготовке, истории c интервью, ресурсы для подготовки.
=> Add FAANG Interview

README.md
**FAANG Tech Interview**:
_https://t.me/FaangTechInterview_
Любі друзі! Это украинская техническая группа-спутник t.me/FaangInterview. Цель группы: обсуждение алгоритмических задач.
=> Add FAANG Tech Interview

README.md
**Art Flutter**:
_https://t.me/artflutter_
Ukrainian community of Flutter enthusiasts
=> Add Art Flutter

README.md
**K8s DevOps chat - Ukraine**:
_https://t.me/k8sdevopsUA_
Чат обговорення Kubernetes.
=> Add K8s DevOps chat - Ukraine

README.md
**UAGolang**:
_https://www.meetup.com/uagolang/_
Ukrainian Golang User Groups
- [+] I have read and understood the [contribution rules](CONTRIBUTING.md). My submission complies with these rules.
- [+] My submission is graMmatically correct.
- [+] My submission follows the [general Awesome List guidelines](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md). You can check it running the [Awesome Lint](https://github.com/sindresorhus/awesome-lint) locally. We also run linter on CI.
=> add UAGolang

README.md
Re-organize the list:
* Remove "By Location" folder in favor of specialities
* Sort alphabetically
=> Remove location branch, sort alphabetically

README.md
Flutter is mostly mobile development at this time.
=> Flutter: frontend --> mobile

README.md
**Ukrainian Data Community Kyiv**:
_https://www.facebook.com/groups/kssug/_
Ukrainian Data Community Kyiv (former Kyiv SQL Server User Group)
=> Add Ukrainian Data Community Kyiv

README.md
**Kyiv Data Science chat**:
_[https://t.me/kyivdatascience]_
[Київський чат Data scientists з періодичними офлайн-мітапами]
- [+] I have read and understood the [contribution rules](CONTRIBUTING.md). My submission complies with these rules.
- [+] My submission is grammatically correct.
- [+] My submission follows the [general Awesome List guidelines](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md). You can check it running the [Awesome Lint](https://github.com/sindresorhus/awesome-lint) locally. We also run linter on CI.
=> Add Kyiv data science telegram chat

README.md
=> Remove age check linter rule

README.md
**[JavaScript testing]**:
_[https://t.me/js_for_testing]_
[Ukrainian JS testing community]
Sorry, I accidentally merged a PR into `main` in my forked repo, please - let me know if this is a problem 🙏 
- [x ] I have read and understood the [contribution rules](CONTRIBUTING.md). My submission complies with these rules.
- [x ] My submission is grammatically correct.
- [x ] My submission follows the [general Awesome List guidelines](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md). You can check it running the [Awesome Lint](https://github.com/sindresorhus/awesome-lint) locally. We also run linter on CI.
=> Add UA JS testing community

README.md
Remove CI badges to comply with https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md
=> Remove CI badges

README.md
**Lviv Python Community**:
_https://t.me/lviv_python_community_
Lviv Python Community. Група для обговорення та поширення досвіду.
=> Add Lviv Python Community

README.md
Scala Ukraine:
[Scala Ukraine Telegram](https://t.me/scala_ukraine)
The community is about development with Scala programming language and all the things related.
=> Add Scala telegram chat link

README.md
**NestJS Ukraine 🇺🇦**, **Terraform Ukraine 🇺🇦**
_https://t.me/nest_ukraine_, _https://t.me/terraform_ukraine_
[Explain what your community is about]
Added two communities:
- Група для прихильників Terraform українського IT-community
- Група для прихильників NestJS українського IT-community
=> Додав Terraform & NestJS телеграм групи

README.md
**Вивчаємо Rust Разом 🇺🇦**:
https://t.me/rustlang_ua
🦀 Українська гілка спільноти Rust ентузіастів 💙💛
Mode information about this community: https://t.me/rustlang_ua/2383
=> Add Rust ua community

README.md
**[NodeUA - JavaScript and Node.js in Ukraine]**:
_[https://t.me/nodeua]_
[Чат спільноти Metarhia, чат по Javascript, Node.js, а також всім сумісним IT-тематикам]
=> Add Node.js and Javascript Metarhia community

README.md
Fixes https://github.com/grem11n/awesome-it-communities-ua/issues/42
=> Remove stale data science community

README.md
[**Laravel UA**]:
_[https://t.me/laravel_ua]_
[Спільнота про Laravel Framework, його складові та додатки]
=> Add 'Laravel UA' group

.github/workflows/main.yml, README.md
Removing a link that doesn't exist any more. Fixes https://github.com/grem11n/awesome-it-communities-ua/issues/46
=> Remove K8s DevOps chat that doesn't exist

README.md
**Ruby UA**:
_https://t.me/ruby4you_
Вивчаємо Ruby разом
=> Add Ruby UA telegram group

README.md
**GolangUA**:
_https://t.me/golang_ua_official_
Ця спільнота є одним з каналів зв'язку Golang community в Україні
=> Add GolangUA telegram chat

README.md
**JavaScript.Ninja**
_https://t.me/javascript_ninja_ 
Чат про JavaScript та Frontend розробку
=> Add JavaScript.Ninja group

.github/workflows/main.yml, README.md, mkdocs.yml
- Refactor the code into a better structure.
- Add a new logo
- Add an info banner
- Add some cosmetic gimmick like emojis.
=> Refactoring

README.md
Add DevOps & QA channels from DOU.
=> Add mode DOU channels

requirements.txt
Update `requirements.txt` for Netlify.
=> Update pip requirements for Netlify

mkdocs.yml
Update colors for the website on MKDocs.
=> Update MKDocs colors

README.md
Removing a stale community, which doesn't exist any more.
=> Remove Kyiv Data Science community since the link doesn't exist

README.md
**Алгоритми | Algoua**:
https://algoua.com
Спільнота, де вивчають та обговорюють алгоритми.
=> Add Algoua
